// Master Materials & PDF Library Data
window.IELTS_GDRIVE_URL = "https://drive.google.com/drive/folders/1Rqj5kBawXG6yC3gFM6im76Ac8IxO0aPx?usp=sharing";
window.IELTS_MATERIALS_DATA = [
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 10 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 10",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "4 authentic examination papers with full audio scripts, answer keys, and candidate writing samples.",
    "filename": "01. Cambridge IELTS 10 Academic.pdf",
    "size_mb": 10.25,
    "rel_path": "01. Cambridge Tests/01. Cambridge IELTS 10 Academic.pdf",
    "gdrive_id": "1N6hR141jDbRjuJDLhxMmRbOHhOL3-QGz",
    "gdrive_url": "https://drive.google.com/file/d/1N6hR141jDbRjuJDLhxMmRbOHhOL3-QGz/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1N6hR141jDbRjuJDLhxMmRbOHhOL3-QGz/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 11 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 11",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Official Cambridge practice examination papers with audio scripts, answer keys, and scoring guides.",
    "filename": "02. Cambridge IELTS 11 Academic.pdf",
    "size_mb": 10.85,
    "rel_path": "01. Cambridge Tests/02. Cambridge IELTS 11 Academic.pdf",
    "gdrive_id": "1u8tPUsDaUhzpLWjwXihtSGGrE1YvDXDz",
    "gdrive_url": "https://drive.google.com/file/d/1u8tPUsDaUhzpLWjwXihtSGGrE1YvDXDz/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1u8tPUsDaUhzpLWjwXihtSGGrE1YvDXDz/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 12 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 12",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "4 authentic examination papers with full answer keys, transcripts, and examiner scoring rubrics.",
    "filename": "04. Cambridge IELTS 12 Academic.pdf",
    "size_mb": 4.14,
    "rel_path": "01. Cambridge Tests/04. Cambridge IELTS 12 Academic.pdf",
    "gdrive_id": "1pRnAQPMfPigN3tmAsQ1-pSH4MahOjdGN",
    "gdrive_url": "https://drive.google.com/file/d/1pRnAQPMfPigN3tmAsQ1-pSH4MahOjdGN/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1pRnAQPMfPigN3tmAsQ1-pSH4MahOjdGN/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 13 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 13",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Complete authentic examination papers with full audio scripts and model writing responses.",
    "filename": "06. Cambridge IELTS 13 Academic.pdf",
    "size_mb": 4.11,
    "rel_path": "01. Cambridge Tests/06. Cambridge IELTS 13 Academic.pdf",
    "gdrive_id": "1pBEyIBVNbn-vkg3oNYOQk-wt_hOPXpsj",
    "gdrive_url": "https://drive.google.com/file/d/1pBEyIBVNbn-vkg3oNYOQk-wt_hOPXpsj/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1pBEyIBVNbn-vkg3oNYOQk-wt_hOPXpsj/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 14 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 14",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Official examination papers from Cambridge Assessment English with audio transcripts and scoring keys.",
    "filename": "08. Cambridge IELTS 14 Academic.pdf",
    "size_mb": 4.59,
    "rel_path": "01. Cambridge Tests/08. Cambridge IELTS 14 Academic.pdf",
    "gdrive_id": "1M4T4bpcKfzLyJQ59S2PZlVaQ0erYh8M2",
    "gdrive_url": "https://drive.google.com/file/d/1M4T4bpcKfzLyJQ59S2PZlVaQ0erYh8M2/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1M4T4bpcKfzLyJQ59S2PZlVaQ0erYh8M2/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 15 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 15",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Authentic practice tests with answers, sample writing responses, audio scripts, and score analysis.",
    "filename": "10. Cambridge IELTS 15 Academic.pdf",
    "size_mb": 10.65,
    "rel_path": "01. Cambridge Tests/10. Cambridge IELTS 15 Academic.pdf",
    "gdrive_id": "1IAAgdWb6ikDwKzoh9dKM3fZqFq_sBFky",
    "gdrive_url": "https://drive.google.com/file/d/1IAAgdWb6ikDwKzoh9dKM3fZqFq_sBFky/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1IAAgdWb6ikDwKzoh9dKM3fZqFq_sBFky/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 16 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 16",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "4 authentic academic test papers with scoring rubrics, complete audio transcripts, and answer keys.",
    "filename": "12. Cambridge IELTS 16 Academic.pdf",
    "size_mb": 6.62,
    "rel_path": "01. Cambridge Tests/12. Cambridge IELTS 16 Academic.pdf",
    "gdrive_id": "10DrDaNYKYrMHsn0_HhvvXS9pqVRtUurj",
    "gdrive_url": "https://drive.google.com/file/d/10DrDaNYKYrMHsn0_HhvvXS9pqVRtUurj/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/10DrDaNYKYrMHsn0_HhvvXS9pqVRtUurj/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 17 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 17",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Official Cambridge examination papers with answers and comprehensive test explanations.",
    "filename": "14. Cambridge IELTS 17 Academic.pdf",
    "size_mb": 10,
    "rel_path": "01. Cambridge Tests/14. Cambridge IELTS 17 Academic.pdf",
    "gdrive_id": "1-7NOHiXSWuaVyUPj7TPsmWLH9e3yMOED",
    "gdrive_url": "https://drive.google.com/file/d/1-7NOHiXSWuaVyUPj7TPsmWLH9e3yMOED/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1-7NOHiXSWuaVyUPj7TPsmWLH9e3yMOED/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 18 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 18",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Authentic exam papers featuring genuine questions, model writing essays, and full transcripts.",
    "filename": "16. Cambridge IELTS 18 Academic.pdf",
    "size_mb": 6.99,
    "rel_path": "01. Cambridge Tests/16. Cambridge IELTS 18 Academic.pdf",
    "gdrive_id": "1jiRBFTR33Mk4ynVyKyP6I6fXlvefdq2D",
    "gdrive_url": "https://drive.google.com/file/d/1jiRBFTR33Mk4ynVyKyP6I6fXlvefdq2D/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1jiRBFTR33Mk4ynVyKyP6I6fXlvefdq2D/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 19 Academic — Authentic Practice Tests",
    "badge": "CAMBRIDGE 19",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Latest official Cambridge examination papers with comprehensive answer keys and audio scripts.",
    "filename": "18. Cambridge IELTS 19 Academic.pdf",
    "size_mb": 6.83,
    "rel_path": "01. Cambridge Tests/18. Cambridge IELTS 19 Academic.pdf",
    "gdrive_id": "1e5iO1qMszZB3R1w3izTIuiKhq7rVHCei",
    "gdrive_url": "https://drive.google.com/file/d/1e5iO1qMszZB3R1w3izTIuiKhq7rVHCei/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1e5iO1qMszZB3R1w3izTIuiKhq7rVHCei/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS 20 Academic — Advanced Study Edition",
    "badge": "CAMBRIDGE 20",
    "badgeColor": "badge-cyan",
    "icon": "fa-graduation-cap",
    "description": "Advance authentic examination papers and question sets for upcoming IELTS exam preparation.",
    "filename": "20. Cambridge IELTS 20 Academic (Preview Edition).pdf",
    "size_mb": 43.87,
    "rel_path": "01. Cambridge Tests/20. Cambridge IELTS 20 Academic (Preview Edition).pdf",
    "gdrive_id": "1eECuX-ozCdLNJ9-GHlcvv5dD-ATjBLC-",
    "gdrive_url": "https://drive.google.com/file/d/1eECuX-ozCdLNJ9-GHlcvv5dD-ATjBLC-/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1eECuX-ozCdLNJ9-GHlcvv5dD-ATjBLC-/preview"
  },
  {
    "category": "01. Cambridge Tests",
    "title": "Cambridge IELTS Listening 1-17 Master Audio Compendium",
    "badge": "LISTENING 1-17",
    "badgeColor": "badge-cyan",
    "icon": "fa-headphones",
    "description": "Ultimate all-in-one listening compilation and transcripts spanning Cambridge 1 through 17.",
    "filename": "22. Cambridge IELTS Listening 1-17 Master Compendium.pdf",
    "size_mb": 121.22,
    "rel_path": "01. Cambridge Tests/22. Cambridge IELTS Listening 1-17 Master Compendium.pdf",
    "gdrive_id": "1hV4L8nL6PBSa72bWjgMhVe2lR1XKHdaf",
    "gdrive_url": "https://drive.google.com/file/d/1hV4L8nL6PBSa72bWjgMhVe2lR1XKHdaf/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1hV4L8nL6PBSa72bWjgMhVe2lR1XKHdaf/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "1200 Most Commonly Repeated IELTS Listening Words",
    "badge": "LISTENING CORE",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Essential high-frequency spelling & keyword checklist for IELTS Listening Sections 1 through 4.",
    "filename": "1200_most_commonly_repeated_words.pdf",
    "size_mb": 0.13,
    "rel_path": "02. Vocabulary & Idioms/1200_most_commonly_repeated_words.pdf",
    "gdrive_id": "1AL89xbtZUsCowDqY4VTj6KrYQ6d2kmkr",
    "gdrive_url": "https://drive.google.com/file/d/1AL89xbtZUsCowDqY4VTj6KrYQ6d2kmkr/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1AL89xbtZUsCowDqY4VTj6KrYQ6d2kmkr/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "IELTS Vocabulary Master Collection (Part 1 to 5)",
    "badge": "VOCAB MASTER",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Comprehensive topic-wise vocabulary compilation with Bangla definitions, collocations & usage.",
    "filename": "685944545_Ielts_Vocabulary_Banglay_IELTS_2023_Part_1_to_Part_5_1.pdf",
    "size_mb": 5.96,
    "rel_path": "02. Vocabulary & Idioms/685944545_Ielts_Vocabulary_Banglay_IELTS_2023_Part_1_to_Part_5_1.pdf",
    "gdrive_id": "1McMmauby37nwqwVxwzzjOOrJqv8Q5blI",
    "gdrive_url": "https://drive.google.com/file/d/1McMmauby37nwqwVxwzzjOOrJqv8Q5blI/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1McMmauby37nwqwVxwzzjOOrJqv8Q5blI/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "800 Essential Idioms & Phrases for IELTS Speaking 7+",
    "badge": "IDIOMS 800",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Natural idiomatic expressions with contextual meanings and usage examples for higher fluency bands.",
    "filename": "800 idioms.pdf",
    "size_mb": 1.17,
    "rel_path": "02. Vocabulary & Idioms/800 idioms.pdf",
    "gdrive_id": "1StWConLDaXQckz54oU99N7SU046RQG2A",
    "gdrive_url": "https://drive.google.com/file/d/1StWConLDaXQckz54oU99N7SU046RQG2A/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1StWConLDaXQckz54oU99N7SU046RQG2A/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "Band 9 Topic-wise Academic Vocabulary Guide",
    "badge": "BAND 9 VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "High-level lexical resource items categorized by all common IELTS essay and speaking topics.",
    "filename": "Band 9 Topic Vocabulary.pdf",
    "size_mb": 5.65,
    "rel_path": "02. Vocabulary & Idioms/Band 9 Topic Vocabulary.pdf",
    "gdrive_id": "1D2RxMqEtzY_LBm-1KZpAl69nwP1l4145",
    "gdrive_url": "https://drive.google.com/file/d/1D2RxMqEtzY_LBm-1KZpAl69nwP1l4145/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1D2RxMqEtzY_LBm-1KZpAl69nwP1l4145/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "IELTS Vocabulary Quick Revision & Study Guide",
    "badge": "REVISION GUIDE",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "High-yield vocabulary revision notes with contextual exam practice by Banglay IELTS.",
    "filename": "Banglay IELTS Vocabulary Study  Revision.pdf",
    "size_mb": 1.87,
    "rel_path": "02. Vocabulary & Idioms/Banglay IELTS Vocabulary Study  Revision.pdf",
    "gdrive_id": "1LzV2csimSOWoJy-UE1LaH7rEYeM-g7rV",
    "gdrive_url": "https://drive.google.com/file/d/1LzV2csimSOWoJy-UE1LaH7rEYeM-g7rV/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1LzV2csimSOWoJy-UE1LaH7rEYeM-g7rV/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "Cambridge IELTS 18 Academic Vocabulary Compendium",
    "badge": "CAM 18 VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Extracted difficult words, synonyms, and paraphrasing traps from Cambridge 18 test papers.",
    "filename": "Cambridge 18 Vocabulary.pdf",
    "size_mb": 0.62,
    "rel_path": "02. Vocabulary & Idioms/Cambridge 18 Vocabulary.pdf",
    "gdrive_id": "1YVIIimRyE40W0pi1o9-FbRkaHFS-u10C",
    "gdrive_url": "https://drive.google.com/file/d/1YVIIimRyE40W0pi1o9-FbRkaHFS-u10C/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1YVIIimRyE40W0pi1o9-FbRkaHFS-u10C/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "Cambridge IELTS 19 Academic Vocabulary & Synonyms",
    "badge": "CAM 19 VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Test-by-test lexical resource breakdown and definitions from Cambridge 19 by Easy IELTS BD.",
    "filename": "Cambridge 19 Vocabulary- Easy IELTS BD.pdf",
    "size_mb": 6.36,
    "rel_path": "02. Vocabulary & Idioms/Cambridge 19 Vocabulary- Easy IELTS BD.pdf",
    "gdrive_id": "14XpSX-kmo_5TKrkmeht9L0J_pEF3t5SJ",
    "gdrive_url": "https://drive.google.com/file/d/14XpSX-kmo_5TKrkmeht9L0J_pEF3t5SJ/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/14XpSX-kmo_5TKrkmeht9L0J_pEF3t5SJ/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "Cambridge Academic Reading Vocabulary Masterlist",
    "badge": "READING VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "High-frequency academic reading terms, contextual meanings, and paraphrasing clues.",
    "filename": "Cambridge Reading Vocabulary.pdf",
    "size_mb": 0.64,
    "rel_path": "02. Vocabulary & Idioms/Cambridge Reading Vocabulary.pdf",
    "gdrive_id": "1_Ug7cJ_UKfajsCUNT-6n9Xjt29nX9gfB",
    "gdrive_url": "https://drive.google.com/file/d/1_Ug7cJ_UKfajsCUNT-6n9Xjt29nX9gfB/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1_Ug7cJ_UKfajsCUNT-6n9Xjt29nX9gfB/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "English Collocations in Use (Advanced — Cambridge)",
    "badge": "COLLOCATIONS ADV",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Cambridge official guide to natural word combinations for achieving Band 7.5 to 9 in Lexical Resource.",
    "filename": "English-Collocations-in-Use-Advanced.pdf",
    "size_mb": 3.38,
    "rel_path": "02. Vocabulary & Idioms/English-Collocations-in-Use-Advanced.pdf",
    "gdrive_id": "1XgB5htaF-oKLkAdA-GQJ3ig1hs-aMJaf",
    "gdrive_url": "https://drive.google.com/file/d/1XgB5htaF-oKLkAdA-GQJ3ig1hs-aMJaf/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1XgB5htaF-oKLkAdA-GQJ3ig1hs-aMJaf/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "English Collocations in Use (Intermediate — Cambridge)",
    "badge": "COLLOCATIONS INT",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Essential collocations to eliminate awkward phrasing in IELTS Writing and Speaking.",
    "filename": "English-Collocations-in-Use-Intermediate.pdf",
    "size_mb": 17.66,
    "rel_path": "02. Vocabulary & Idioms/English-Collocations-in-Use-Intermediate.pdf",
    "gdrive_id": "1m6FKxbF8QYz_cwiEtAp2SrFx9iweIJGV",
    "gdrive_url": "https://drive.google.com/file/d/1m6FKxbF8QYz_cwiEtAp2SrFx9iweIJGV/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1m6FKxbF8QYz_cwiEtAp2SrFx9iweIJGV/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "IELTS Listening Map & Diagram Vocabulary (Band 8+)",
    "badge": "MAP VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Directional prepositions, orientation terms, and plan-labeling keywords for Section 2 maps.",
    "filename": "Listening Map Vocabulary- Band 8.pdf",
    "size_mb": 0.81,
    "rel_path": "02. Vocabulary & Idioms/Listening Map Vocabulary- Band 8.pdf",
    "gdrive_id": "13x7ZEvHSF_ofLdJCbmeemUYOf_anziCQ",
    "gdrive_url": "https://drive.google.com/file/d/13x7ZEvHSF_ofLdJCbmeemUYOf_anziCQ/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/13x7ZEvHSF_ofLdJCbmeemUYOf_anziCQ/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "IELTS Listening Core Keywords & Spelling Guide",
    "badge": "LISTENING WORDS",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Commonly misspelled words, plural forms, and numerical keywords in IELTS Listening.",
    "filename": "Listening useful words.pdf",
    "size_mb": 0.11,
    "rel_path": "02. Vocabulary & Idioms/Listening useful words.pdf",
    "gdrive_id": "1Zo59g8V0jwixSolcNr5DD1zrkgbJCh10",
    "gdrive_url": "https://drive.google.com/file/d/1Zo59g8V0jwixSolcNr5DD1zrkgbJCh10/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1Zo59g8V0jwixSolcNr5DD1zrkgbJCh10/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "IELTS Academic Vocabulary by Key Topics",
    "badge": "TOPIC VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Organized lexical resources for Education, Technology, Environment, Health, and Society.",
    "filename": "Vocabulary by Topics.pdf",
    "size_mb": 1.4,
    "rel_path": "02. Vocabulary & Idioms/Vocabulary by Topics.pdf",
    "gdrive_id": "1z_ZTQR2uM-esNNF7igk_8oIGoEbAQRkw",
    "gdrive_url": "https://drive.google.com/file/d/1z_ZTQR2uM-esNNF7igk_8oIGoEbAQRkw/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1z_ZTQR2uM-esNNF7igk_8oIGoEbAQRkw/preview"
  },
  {
    "category": "02. Vocabulary & Idioms",
    "title": "Cambridge IELTS 6-13 Comprehensive Vocabulary Compendium",
    "badge": "CAM 6-13 VOCAB",
    "badgeColor": "badge-indigo",
    "icon": "fa-spell-check",
    "description": "Complete vocabulary compilation and collocations extracted across Cambridge 6 through 13.",
    "filename": "cambridge 6-13 Vocabulary.pdf",
    "size_mb": 7.59,
    "rel_path": "02. Vocabulary & Idioms/cambridge 6-13 Vocabulary.pdf",
    "gdrive_id": "10wZ1GEjERfF7NUklM19PvoARR7_opVVo",
    "gdrive_url": "https://drive.google.com/file/d/10wZ1GEjERfF7NUklM19PvoARR7_opVVo/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/10wZ1GEjERfF7NUklM19PvoARR7_opVVo/preview"
  },
  {
    "category": "03. Writing",
    "title": "1000 Quick Writing Ideas for Task 1 & Task 2",
    "badge": "1000 IDEAS",
    "badgeColor": "badge-purple",
    "icon": "fa-pen-nib",
    "description": "Ready brainstorming points, arguments, and counter-arguments for all common essay topics.",
    "filename": "1000 Quick Writing Ideas.pdf",
    "size_mb": 1.68,
    "rel_path": "03. Writing/1000 Quick Writing Ideas.pdf",
    "gdrive_id": "1FbHs4DzL1PtMW5dTFUVFdG6oyor1aR0D",
    "gdrive_url": "https://drive.google.com/file/d/1FbHs4DzL1PtMW5dTFUVFdG6oyor1aR0D/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1FbHs4DzL1PtMW5dTFUVFdG6oyor1aR0D/preview"
  },
  {
    "category": "03. Writing",
    "title": "Ideas & Arguments for IELTS Writing Task 2 (Band 8+)",
    "badge": "TASK 2 IDEAS",
    "badgeColor": "badge-purple",
    "icon": "fa-pen-nib",
    "description": "Deep-dive brainstorming guide with thesis statements and topic sentences for high-band essays.",
    "filename": "IDEAS for Writing Task 2.pdf",
    "size_mb": 31.78,
    "rel_path": "03. Writing/IDEAS for Writing Task 2.pdf",
    "gdrive_id": "13yXv36dX5GafAMDFTEuxchkJfEkbW5Jw",
    "gdrive_url": "https://drive.google.com/file/d/13yXv36dX5GafAMDFTEuxchkJfEkbW5Jw/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/13yXv36dX5GafAMDFTEuxchkJfEkbW5Jw/preview"
  },
  {
    "category": "03. Writing",
    "title": "IELTS Writing Task 1 Academic Vocabulary & Trends",
    "badge": "TASK 1 VOCAB",
    "badgeColor": "badge-purple",
    "icon": "fa-pen-nib",
    "description": "Upward/downward trends, fluctuations, comparative structures, and proportion terms for Task 1 reports.",
    "filename": "IELTS Writing Task-1 Vocabulary.pdf",
    "size_mb": 0.93,
    "rel_path": "03. Writing/IELTS Writing Task-1 Vocabulary.pdf",
    "gdrive_id": "1ZDn21Ec2gLdZALWawQUQ5LMD_wysujfQ",
    "gdrive_url": "https://drive.google.com/file/d/1ZDn21Ec2gLdZALWawQUQ5LMD_wysujfQ/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1ZDn21Ec2gLdZALWawQUQ5LMD_wysujfQ/preview"
  },
  {
    "category": "03. Writing",
    "title": "Mastering Paraphrasing in IELTS Writing Task 2",
    "badge": "PARAPHRASING",
    "badgeColor": "badge-purple",
    "icon": "fa-pen-nib",
    "description": "Sentence inversion, synonym substitution, and grammar shifts for band 8+ introductions.",
    "filename": "Mastering Paraphrasing in IELTS Writing Task 2.pdf",
    "size_mb": 0.12,
    "rel_path": "03. Writing/Mastering Paraphrasing in IELTS Writing Task 2.pdf",
    "gdrive_id": "1R2GBMfyVtQLqCwDdjFn8KFMVRglSF68C",
    "gdrive_url": "https://drive.google.com/file/d/1R2GBMfyVtQLqCwDdjFn8KFMVRglSF68C/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1R2GBMfyVtQLqCwDdjFn8KFMVRglSF68C/preview"
  },
  {
    "category": "03. Writing",
    "title": "IELTS Liz Essay Ideas & Model Arguments",
    "badge": "LIZ ESSAY IDEAS",
    "badgeColor": "badge-purple",
    "icon": "fa-pen-nib",
    "description": "Essential essay structures, balanced view arguments, and band 9 topic solutions by IELTS Liz.",
    "filename": "liz's ideas for essay.pdf",
    "size_mb": 6.85,
    "rel_path": "03. Writing/liz's ideas for essay.pdf",
    "gdrive_id": "1z8Q2VAbEjps6GZVUEFdRi2AIQSYpO6bw",
    "gdrive_url": "https://drive.google.com/file/d/1z8Q2VAbEjps6GZVUEFdRi2AIQSYpO6bw/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1z8Q2VAbEjps6GZVUEFdRi2AIQSYpO6bw/preview"
  },
  {
    "category": "04. Speaking",
    "title": "Makkar IELTS Speaking Cue Cards & Follow-ups (Jan-Apr 2025)",
    "badge": "SPEAKING 2025",
    "badgeColor": "badge-pink",
    "icon": "fa-microphone",
    "description": "Latest official exam prediction topics for Part 1, Part 2 cue cards, and Part 3 follow-ups with answers.",
    "filename": "2025 Kiran Makkar Speaking Cue Cards 1st Version Jan-Apr2025.pdf",
    "size_mb": 49.37,
    "rel_path": "04. Speaking/2025 Kiran Makkar Speaking Cue Cards 1st Version Jan-Apr2025.pdf",
    "gdrive_id": "10H_roMqXTo7VGQ33mVPdzQFPdFkwLHY6",
    "gdrive_url": "https://drive.google.com/file/d/10H_roMqXTo7VGQ33mVPdzQFPdFkwLHY6/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/10H_roMqXTo7VGQ33mVPdzQFPdFkwLHY6/preview"
  },
  {
    "category": "05. Reading",
    "title": "IELTS Reading Recent Actual Tests with Full Explanations",
    "badge": "ACTUAL TESTS",
    "badgeColor": "badge-emerald",
    "icon": "fa-glasses",
    "description": "Full-length authentic passages with question-by-question explanations and scoring criteria.",
    "filename": "IELTS_General_Reading_Recent_Actual_Tests_with_Answers.pdf",
    "size_mb": 3.99,
    "rel_path": "05. Reading/IELTS_General_Reading_Recent_Actual_Tests_with_Answers.pdf",
    "gdrive_id": "145XJKfW_3FfGsBsh6Ygnps5RhZveiiK9",
    "gdrive_url": "https://drive.google.com/file/d/145XJKfW_3FfGsBsh6Ygnps5RhZveiiK9/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/145XJKfW_3FfGsBsh6Ygnps5RhZveiiK9/preview"
  },
  {
    "category": "05. Reading",
    "title": "IELTS রিডিং সহজে বোঝার গোপন কৌশল ও স্পিড রিডিং টেকনিক",
    "badge": "READING TACTICS",
    "badgeColor": "badge-emerald",
    "icon": "fa-glasses",
    "description": "স্কিমিং, স্ক্যানিং, ট্রু/ফলস/নট গিভেন ট্র্যাপ ও কি-ওয়ার্ড লোকেট করার সহজ বাংলা গাইড।",
    "filename": "রিডিং_সহজে_বোঝার_কৌশল_Easy_IELTS_BD_www_easyieltsbd_com.pdf",
    "size_mb": 3.92,
    "rel_path": "05. Reading/রিডিং_সহজে_বোঝার_কৌশল_Easy_IELTS_BD_www_easyieltsbd_com.pdf",
    "gdrive_id": "1WCj1Lui1xrDfO6i9NFuy5fi33owwWLSA",
    "gdrive_url": "https://drive.google.com/file/d/1WCj1Lui1xrDfO6i9NFuy5fi33owwWLSA/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1WCj1Lui1xrDfO6i9NFuy5fi33owwWLSA/preview"
  },
  {
    "category": "06. Grammar & Foundation",
    "title": "Common Mistakes at IELTS Intermediate (Cambridge)",
    "badge": "COMMON MISTAKES",
    "badgeColor": "badge-amber",
    "icon": "fa-cubes",
    "description": "Highlights real candidate errors in subject-verb agreement, tenses, and prepositions with corrections.",
    "filename": "Common Mistakes at IELTS Intermediate.pdf",
    "size_mb": 1.72,
    "rel_path": "06. Grammar & Foundation/Common Mistakes at IELTS Intermediate.pdf",
    "gdrive_id": "1c5RPTYLwBKEYTXxuhNb7Zo22jDhaGCG0",
    "gdrive_url": "https://drive.google.com/file/d/1c5RPTYLwBKEYTXxuhNb7Zo22jDhaGCG0/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1c5RPTYLwBKEYTXxuhNb7Zo22jDhaGCG0/preview"
  },
  {
    "category": "06. Grammar & Foundation",
    "title": "Easy Rules of Complex Sentences for IELTS Writing",
    "badge": "COMPLEX RULES",
    "badgeColor": "badge-amber",
    "icon": "fa-cubes",
    "description": "Relative clauses, conditional structures, and subordinating conjunctions for high grammatical range.",
    "filename": "Easy Rules of Complex Sentences- Easy IELTS BD.pdf",
    "size_mb": 0.44,
    "rel_path": "06. Grammar & Foundation/Easy Rules of Complex Sentences- Easy IELTS BD.pdf",
    "gdrive_id": "1kni6IyDhCaMFtMvAJfG5m4pkWUF4Laxq",
    "gdrive_url": "https://drive.google.com/file/d/1kni6IyDhCaMFtMvAJfG5m4pkWUF4Laxq/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1kni6IyDhCaMFtMvAJfG5m4pkWUF4Laxq/preview"
  },
  {
    "category": "06. Grammar & Foundation",
    "title": "Cambridge Mindset for IELTS (Foundation Coursebook)",
    "badge": "MINDSET FOUNDATION",
    "badgeColor": "badge-amber",
    "icon": "fa-cubes",
    "description": "Cambridge official foundation course to build core language proficiency from band 4.5 to 6.5.",
    "filename": "MINDSET For IELTS-Foundation.pdf",
    "size_mb": 19.72,
    "rel_path": "06. Grammar & Foundation/MINDSET For IELTS-Foundation.pdf",
    "gdrive_id": "1lrkYo6JJ_hS07DKGrCFAFcChi_oxfBXk",
    "gdrive_url": "https://drive.google.com/file/d/1lrkYo6JJ_hS07DKGrCFAFcChi_oxfBXk/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1lrkYo6JJ_hS07DKGrCFAFcChi_oxfBXk/preview"
  },
  {
    "category": "06. Grammar & Foundation",
    "title": "ঘরে বসে IELTS প্রস্তুতি — মুনজেরিন শহীদ (10 Minute School)",
    "badge": "MUNZEREEN IELTS",
    "badgeColor": "badge-amber",
    "icon": "fa-cubes",
    "description": "বাংলা ভাষায় চার মডিউলের বিস্তারিত গাইডলাইন, কমন ভুলত্রুটি ও প্র্যাকটিস রুটিন (কম্প্রেসড সংস্করণ)।",
    "filename": "ঘরে বসে ILTS প্রস্তুতি মুনজেরিন শহিদ_compressed.pdf",
    "size_mb": 60.75,
    "rel_path": "06. Grammar & Foundation/ঘরে বসে ILTS প্রস্তুতি মুনজেরিন শহিদ_compressed.pdf",
    "gdrive_id": "1-KTrikxvHc3oNMwa72IPn7X8nwBiCx3U",
    "gdrive_url": "https://drive.google.com/file/d/1-KTrikxvHc3oNMwa72IPn7X8nwBiCx3U/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1-KTrikxvHc3oNMwa72IPn7X8nwBiCx3U/preview"
  },
  {
    "category": "07. Magazines & Extra Reading",
    "title": "The Economist — Global Academic Reading (May 2024)",
    "badge": "THE ECONOMIST",
    "badgeColor": "badge-blue",
    "icon": "fa-newspaper",
    "description": "Complex analytical prose for developing advanced reading speed and comprehension for band 8+.",
    "filename": "The Economist-2024-05-04-PDF.pdf",
    "size_mb": 47.33,
    "rel_path": "07. Magazines & Extra Reading/The Economist-2024-05-04-PDF.pdf",
    "gdrive_id": "19a6QikOg8TG0qF7hYT0lK7aXavuSPm5C",
    "gdrive_url": "https://drive.google.com/file/d/19a6QikOg8TG0qF7hYT0lK7aXavuSPm5C/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/19a6QikOg8TG0qF7hYT0lK7aXavuSPm5C/preview"
  },
  {
    "category": "07. Magazines & Extra Reading",
    "title": "TIME Magazine — Global Essays & Analysis (May 2024)",
    "badge": "TIME MAGAZINE",
    "badgeColor": "badge-blue",
    "icon": "fa-newspaper",
    "description": "Authentic journalistic articles on technology, science, and global culture for background reading.",
    "filename": "Time_Magazine may 2024.pdf",
    "size_mb": 59.6,
    "rel_path": "07. Magazines & Extra Reading/Time_Magazine may 2024.pdf",
    "gdrive_id": "1yksM5tzYJXJfOrD05gyVM-m5_s2j53bF",
    "gdrive_url": "https://drive.google.com/file/d/1yksM5tzYJXJfOrD05gyVM-m5_s2j53bF/view?usp=sharing",
    "gdrive_preview": "https://drive.google.com/file/d/1yksM5tzYJXJfOrD05gyVM-m5_s2j53bF/preview"
  }
];
